config/routes.rb
Rails.application.routes.draw do
  resources :games

  devise_for :users
  get 'streams/index'
  root 'streams#index'
  match 'streams/embed' => 'streams#embed', :via => [:get], :as => :stream_embed

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_and_belongs_to_many :users, :join_table => "games_users"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_and_belongs_to_many :games, :join_table => "games_users"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, {game_ids: []}, :number_of_streams_per_page, :number_of_stream_pages )}
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :password, :password_confirmation, :current_password, {game_ids: []},:number_of_streams_per_page, :number_of_stream_pages )}
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    @users = User.all
  end

  # GET /games/1/edit
  def edit
    @users = User.all
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :user_ids => [])
    end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  require 'will_paginate/array'
  def index
    @stream_list = []

    #get unfiltered streams for non logged in user
    unless user_signed_in?
      number_of_streams = 48
      Twitch.streams.all(limit:number_of_streams) do |stream|
        @stream_list.push([stream.preview_url, stream.channel.name, stream.game_name])
      end
      @stream_list = @stream_list.paginate(page:params[:page], per_page:16)
    #use User preferences and get a filtered list of streams
    else
      #get the user's preferences
      user_filter = User.find(current_user).games
      user_filter = user_filter.map{|x| x.name}
      user_streams_per_page = User.find(current_user).number_of_streams_per_page
      user_stream_pages = User.find(current_user).number_of_stream_pages
      #go through top streams, adding streams to the list only if they aren't filtered by the user
      Twitch.streams.all(limit:user_streams_per_page*user_stream_pages*5) do |stream|
        unless user_filter.include?(stream.game_name)
          @stream_list.push([stream.preview_url, stream.channel.name, stream.game_name])
        end
        break if @stream_list.length >= user_streams_per_page*user_stream_pages #limit the total number of streams to the list
      end
      @stream_list = @stream_list.paginate(page:params[:page], per_page:user_streams_per_page)
    end
  end

  def embed
    @stream_name = params[:stream_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container">
<div class="collapse navbar-collapse">
<ul class="nav navbar-nav navbar-left">
	<li>
		<%= link_to "/" do %>
			<button class="btn btn-default"%> Home</button>
		<% end %>
	</li>
</ul>
<ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
		<li>
		<% user_email = user = User.find(current_user).email %>
		<%= link_to edit_user_registration_path do %>
			<button class="btn btn-default"%><%= user_email %></button>
		<% end %>
		</li>
		<li>
		<%= link_to destroy_user_session_path, :method => :delete do %> 
			<button class="btn btn-default">Logout</button>
		<% end %>
		</li>
			<% else %>
		<li>
			<%= link_to new_user_registration_path do %>
			<button class="btn btn-default">Register</button>
		<% end %>
		</li>
		<li> 
		<%= link_to new_user_session_path do %>
			<button class="btn btn-default">Login</button>
		<% end %>
		</li>
	<% end %>
</ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Andy's Stream Browser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/streams/embed.html.erb
<head>
<style>
* { font-family:sans-serif;}
.box { padding: 10px; border:10px; margin:50px; background:#F1F1F1;}
hr { border-color:#6441A5;border-collapse: collapse;}
body { background-color:#262626;}
</style>
</head>
<%= render 'layouts/header' %>
<body>
<div class="box img-rounded">
<p class="all" align="center"> 
<object type="application/x-shockwave-flash" height="720" width="1280" id="live_embed_player_flash" data="http://www.twitch.tv/widgets/live_embed_player.swf?channel=<%=@stream_name%>" bgcolor="#000000"><param name="allowFullScreen" value="true" /><param name="allowScriptAccess" value="always" /><param name="allowNetworking" value="all" /><param name="movie" value="http://www.twitch.tv/widgets/live_embed_player.swf" /><param name="flashvars" value="hostname=www.twitch.tv&channel=<%=@stream_name%>&auto_play=true&start_volume=25" /></object>
</p>
</div>
</body>

app/views/streams/index.html.erb
<head>
<style>
* { font-family:sans-serif;}
.box { padding: 10px; border:10px; margin:50px; background:#F1F1F1;}
hr { border-color:#6441A5;border-collapse: collapse;}
body { background-color:#262626;}
.image_and_text {display:inline-block;}
</style>
</head>
<%= render 'layouts/header' %>
<body>
<div class="box img-rounded">
<h1 align="center">Andy's Stream Browser</h1> 
<%= @temp %>
<hr color=#6441A5>
<%= will_paginate @stream_list%>
<div align="center">
	<% @stream_list.each do |stream_preview, stream_name, stream_game_name| %>
		<div class="image_and_text">
		<div>
		<%= link_to image_tag("#{stream_preview}"), stream_embed_path(:stream_name => stream_name) %>
		</div>
		<div align="left">
		<small><%= stream_game_name %> | <%= stream_name %></small>
		</div>
		</div>
	<% end %>
</div>
<%= will_paginate @stream_list%>
<hr color=#6441A5>
</div>
</body>